Fix step5 compilation error (.data sections)
step5 fails to compile with:

`str' referenced in section `.text' of /tmp/cc0MRQck.o: defined in discarded section `.data.rel.local' of /tmp/cc0MRQck.o
`str' referenced in section `.text' of /tmp/cc0MRQck.o: defined in discarded section `.data.rel.local' of /tmp/cc0MRQck.o
collect2: error: ld returned 1 exit status
make: *** [Makefile:2: build] Error 1

More recent versions of gcc include more sections, which need to be
accounted for in link.lds.